In [48]:
import numpy as np

print('Задача 1.1')
print()

A = np.array([[1, 2], [4, -1]])
print('Матриця A:', A, sep = '\n')
print()

B = np.array([[2, -3],[-4, 1]])
print('Матриця B:', B, sep = '\n')
print()

C = A * B - B * A
print('Матриця C:', C, sep = '\n')
print()

print('Задача 2.1')
print()

A = np.array([[-1, 2],[0, 1]])
print('Матриця A:', A, sep = '\n')
print()

print('Матриця A в квадраті:', pow(A,2), sep = '\n')
print()

print('Задача 3.1')
print()

A = np.array([[3, 5], [6, -1]])
print('Матриця A:', A, sep = '\n')
print()

B = np.array([[2, 1],[-3, 2]])
print('Матриця B:', B, sep = '\n')
print()

print('Добуток матриць A і B', A * B, sep = '\n')
print()

print('Задача 4.1')
print()

A = np.array([[2, 3, 4], [1, 0, 6], [7, 8, 9]])
print('Матриця A:', A, sep = '\n')
print()

A_det = np.linalg.det(A)

print('Визначник матриці A:', format(A_det, '.9g'))

Задача 1.1

Матриця A:
[[ 1  2]
 [ 4 -1]]

Матриця B:
[[ 2 -3]
 [-4  1]]

Матриця C:
[[0 0]
 [0 0]]

Задача 2.1

Матриця A:
[[-1  2]
 [ 0  1]]

Матриця A в квадраті:
[[1 4]
 [0 1]]

Задача 3.1

Матриця A:
[[ 3  5]
 [ 6 -1]]

Матриця B:
[[ 2  1]
 [-3  2]]

Добуток матриць A і B
[[  6   5]
 [-18  -2]]

Задача 4.1

Матриця A:
[[2 3 4]
 [1 0 6]
 [7 8 9]]

Визначник матриці A: 35
