In [7]:
import numpy as np

A = np.matrix([[4, 1, 4], [1, 1, 2], [2, 1, 2]])
B = np.matrix([[-2], [-1], [0]])
print('Матриця А:', A, sep = '\n' )
print()
print('Матриця B:', B, sep = '\n' )
print()

A_rev = np.linalg.inv(A)
print(A_rev)
print()

x = A_rev.dot(B)
print('X:', x, sep = '\n')

Матриця А:
[[4 1 4]
 [1 1 2]
 [2 1 2]]

Матриця B:
[[-2]
 [-1]
 [ 0]]

[[-1.66533454e-16 -1.00000000e+00  1.00000000e+00]
 [-1.00000000e+00 -2.96059473e-16  2.00000000e+00]
 [ 5.00000000e-01  1.00000000e+00 -1.50000000e+00]]

X:
[[ 1.]
 [ 2.]
 [-2.]]
