In [15]:
import numpy as np

A = np.matrix([[4, 1, 4], [1, 1, 2], [2, 1, 2]])
B = np.matrix([[-2], [-1], [0]])
print('Матриця А:', A, sep = '\n' )
print()
print('Матриця B:', B, sep = '\n' )
print()

def kram(A,B):
    det_A = np.linalg.det(A)
    if det_A != 0:
       A1 = np.matrix(A)
       A2 = np.matrix(A)
       A3 = np.matrix(A)
       A1[:, 0] = B
       A2[:, 1] = B
       A3[:, 2] = B
       x = np.linalg.det(A1)/det_A
       y =np.linalg.det(A2)/det_A
       z= np.linalg.det(A3)/det_A
       print('Рішення за Крамером:')
       print('x=',x.round(3),'y=',y.round(3),'z=',z.round(3))
    else:
        print("Визначник дорівнює нулю, система не має розв'язків")
    return x,y,z
kram(A,B)

print()
print('Перевірка правильності розв’язання\n', np.linalg.solve(A,B).round(3))


Матриця А:
[[4 1 4]
 [1 1 2]
 [2 1 2]]

Матриця B:
[[-2]
 [-1]
 [ 0]]

Рішення за Крамером:
x= 1.0 y= 2.0 z= -2.0

Перевірка правильності розв’язання
 [[ 1.]
 [ 2.]
 [-2.]]
