In [20]:
import numpy as np

print('Задача 5.1')
print()

A = np.array([[1, 2, 3, 4], [-2, 1, -4, 3], [3, -4, -1, 2], [4, 3, -2, -1]])
print('Матриця A:', A, sep = '\n')
print()

A_det = np.linalg.det(A)
print('Визначник матриці A:', format(A_det, '.9g'))
print()

print('Задача 6.1')
print()

A = np.array([[1, 2, -3], [0, 1, 2], [0, 0, 1]])
print('Матриця A:', A, sep = '\n')
print()

A_rev = np.linalg.inv(A)
print('Обернена матриця A:', A_rev, sep = '\n')
print()


print('Задача 7.1')
print()

A = np.array([[1, 2, 3, 4], [3, -1, 2, 5], [1, 2, 3, 4], [1, 3, 4, 5]])
print('Матриця A:', A, sep = '\n')
print()

A_rank = np.linalg.matrix_rank(A)
print('Ранг матриці A: ', A_rank)
print()




Задача 5.1

Матриця A:
[[ 1  2  3  4]
 [-2  1 -4  3]
 [ 3 -4 -1  2]
 [ 4  3 -2 -1]]

Визначник матриці A: 900

Задача 6.1

Матриця A:
[[ 1  2 -3]
 [ 0  1  2]
 [ 0  0  1]]

Обернена матриця A:
[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]

Задача 7.1

Матриця A:
[[ 1  2  3  4]
 [ 3 -1  2  5]
 [ 1  2  3  4]
 [ 1  3  4  5]]

Ранг матриці A:  2

